export interface Pokemon {
    _id?: string,
    name: string,
    no: number,
    index: number,
    types: Array<string>,
    level: number,
    atk: number,
    def: number,
    hp: number,
    speed: number,
    spAtk: number,
    spDef: number,
    imgUrl: string,
    price: number,
    prevPrice?: number,
    ownerID?: string,
    forSale: boolean,
}